name: mentor
description: "Discove Your Path"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  archive: ^3.6.1
  bloc: ^8.1.4
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  docx_template: ^0.4.0
  equatable: ^2.0.5
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^10.1.0
  flutter_gen: ^5.10.0
  flutter_markdown: ^0.7.7+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  form_builder_validators: ^11.2.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^8.2.0
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  google_generative_ai: ^0.4.7
  http: ^1.1.0
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.9.0
  logger: ^2.6.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  responsive_builder: ^0.7.1
  step_progress: ^2.6.1
  talker_bloc_logger: ^4.6.4
  universal_html: ^2.2.4
  url_launcher: ^6.3.2
  url_strategy: ^0.3.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svgs/
