// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClT1l9Ra0vcR6Lbdb3qNZS9Cg6BOky-vw',
    appId: '1:319047157578:web:2220ae24d0466f57ef23b3',
    messagingSenderId: '319047157578',
    projectId: 'quiz-c7220',
    authDomain: 'quiz-c7220.firebaseapp.com',
    storageBucket: 'quiz-c7220.firebasestorage.app',
    measurementId: 'G-DNNW10H2VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN4wpuGGy45Yd7zypmNnMVGfeU2rKvclI',
    appId: '1:319047157578:android:58277c444abb66cfef23b3',
    messagingSenderId: '319047157578',
    projectId: 'quiz-c7220',
    storageBucket: 'quiz-c7220.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD69XG5lgOq3AJFAJ-1aocApYAvopK3eqY',
    appId: '1:319047157578:ios:6739986624e27654ef23b3',
    messagingSenderId: '319047157578',
    projectId: 'quiz-c7220',
    storageBucket: 'quiz-c7220.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClT1l9Ra0vcR6Lbdb3qNZS9Cg6BOky-vw',
    appId: '1:319047157578:web:3ee1d639738fbd70ef23b3',
    messagingSenderId: '319047157578',
    projectId: 'quiz-c7220',
    authDomain: 'quiz-c7220.firebaseapp.com',
    storageBucket: 'quiz-c7220.firebasestorage.app',
    measurementId: 'G-M9BYM0WGFH',
  );

}