import 'package:quiz/feature/chat/data/models/assessment_question/assessment_question.dart';

final List<AssessmentQuestion> questions = [
    // المستوى 1 (20 سؤالاً)
    AssessmentQuestion(id: 'Q1', level: 'Level 1', text: 'أستطيع شرح الأفكار المعقدة بمصطلحات بسيطة يسهل على الآخرين فهمها.', kind: QuestionKind.likert, weight: 4, timeSeconds: 25),
    AssessmentQuestion(id: 'Q2', level: 'Level 1', text: 'أبحث بنشاط عن فرص تعلم جديدة لتحسين مهاراتي.', kind: QuestionKind.likert, weight: 4, timeSeconds: 20),
    AssessmentQuestion(id: 'Q3', level: 'Level 1', text: 'عندما ألتزم بموعد نهائي، أتسلم العمل دائمًا في الوقت المحدد.', kind: QuestionKind.likert, weight: 5, timeSeconds: 20),
    AssessmentQuestion(id: 'Q4', level: 'Level 1', text: 'أستمتع بمعالجة المشكلات التي ليس لها حلول واضحة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 25),
    AssessmentQuestion(id: 'Q5', level: 'Level 1', text: 'أتخذ المبادرة لبدء المشاريع دون انتظار تعليمات مفصلة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 30),
    AssessmentQuestion(id: 'Q6', level: 'Level 1', text: 'أقوم بتكييف أسلوبي في التواصل بناءً على من أتحدث معه.', kind: QuestionKind.likert, weight: 4, timeSeconds: 30),
    AssessmentQuestion(id: 'Q7', level: 'Level 1', text: 'أشعر بالراحة عند العمل بشكل مستقل لفترات طويلة.', kind: QuestionKind.likert, weight: 3, timeSeconds: 20),
    AssessmentQuestion(id: 'Q8', level: 'Level 1', text: 'أطرح أسئلة توضيحية عندما تكون التعليمات غير واضحة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 25),
    AssessmentQuestion(id: 'Q9', level: 'Level 1', text: 'أبقى متحمسًا حتى عند العمل في مهام متكررة.', kind: QuestionKind.likert, weight: 3, timeSeconds: 25),
    AssessmentQuestion(id: 'Q10', level: 'Level 1', text: 'أستطيع تحديد السبب الجذري للمشكلات بدلاً من معالجة الأعراض فقط.', kind: QuestionKind.likert, weight: 4, timeSeconds: 35),
    AssessmentQuestion(id: 'Q11', level: 'Level 1', text: 'أسعى بنشاط للحصول على ملاحظات لتحسين جودة عملي.', kind: QuestionKind.likert, weight: 4, timeSeconds: 25),
    AssessmentQuestion(id: 'Q12', level: 'Level 1', text: 'أشعر بالثقة عند تقديم أفكاري للآخرين.', kind: QuestionKind.likert, weight: 3, timeSeconds: 20),
    AssessmentQuestion(id: 'Q13', level: 'Level 1', text: 'أستطيع العمل بفعالية تحت الضغط وفي المواعيد النهائية الضيقة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 25),
    AssessmentQuestion(id: 'Q14', level: 'Level 1', text: 'أتحمل مسؤولية أخطائي دون تقديم أعذار.', kind: QuestionKind.likert, weight: 5, timeSeconds: 25),
    AssessmentQuestion(id: 'Q15', level: 'Level 1', text: 'أستمتع بالتعرف على صناعات ومواضيع خارج تخصصي.', kind: QuestionKind.likert, weight: 3, timeSeconds: 30),
    AssessmentQuestion(id: 'Q16', level: 'Level 1', text: 'ما الذي يحفزك أكثر عند العمل على المشاريع؟', kind: QuestionKind.multipleChoice, weight: 3, timeSeconds: 45, options: ['تعلم مهارات جديدة', 'حل المشكلات الصعبة', 'مساعدة الآخرين على تحقيق أهدافهم', 'إنشاء شيء فريد', 'كسب الاعتراف']),
    AssessmentQuestion(id: 'Q17', level: 'Level 1', text: 'عند مواجهة مهمة صعبة، ما هو غريزتك الأولى؟', kind: QuestionKind.multipleChoice, weight: 4, timeSeconds: 60, options: ['تقسيمها إلى خطوات أصغر', 'طلب المساعدة أو التوجيه', 'البحث عن أمثلة مشابهة', 'بدء التجريب فورًا', 'أخذ وقت للتخطيط بدقة']),
    AssessmentQuestion(id: 'Q18', level: 'Level 1', text: 'كيف تفضل تلقي الملاحظات على عملك؟', kind: QuestionKind.multipleChoice, weight: 2, timeSeconds: 45, options: ['تعليقات مكتوبة مفصلة', 'مناقشة وجهًا لوجه', 'ملاحظات شفهية سريعة', 'أمثلة مرئية للتحسينات', 'التقييم الذاتي متبوعًا بمناقشة']),
    AssessmentQuestion(id: 'Q19', level: 'Level 1', text: 'في أي وقت من اليوم تكون أكثر إنتاجية للعمل المركز؟', kind: QuestionKind.multipleChoice, weight: 2, timeSeconds: 30, options: ['الصباح الباكر (6-9 صباحًا)', 'منتصف الصباح (9-12 ظهرًا)', 'بعد الظهر (12-4 مساءً)', 'المساء (4-8 مساءً)', 'الليل المتأخر (8 مساءً+)']),
    AssessmentQuestion(id: 'Q20', level: 'Level 1', text: 'عند العمل مع العملاء، ما الأهم بالنسبة لك؟', kind: QuestionKind.multipleChoice, weight: 4, timeSeconds: 60, options: ['مواصفات المشروع الواضحة', 'تحديثات التواصل المنتظمة', 'حرية إبداعية في التنفيذ', 'شروط الدفع الفوري', 'بناء علاقات طويلة الأمد']),

    // المستوى 2 (60 سؤالاً)
    AssessmentQuestion(id: 'Q21', level: 'Level 2', text: 'أستطيع التأثير على آراء الآخرين من خلال الحجج المنطقية والأدلة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 30),
    AssessmentQuestion(id: 'Q22', level: 'Level 2', text: 'أبقى هادئًا ومركزًا عندما تنشأ مشكلات غير متوقعة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 30),
    AssessmentQuestion(id: 'Q23', level: 'Level 2', text: 'أشارك بنشاط بالأفكار والحلول في مناقشات الفريق.', kind: QuestionKind.likert, weight: 4, timeSeconds: 30),
    AssessmentQuestion(id: 'Q24', level: 'Level 2', text: 'أستطيع تحديد أولويات المشاريع المتعددة بفعالية مع مواعيد نهائية متنافسة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 35),
    AssessmentQuestion(id: 'Q25', level: 'Level 2', text: 'أستمتع بتوجيه الآخرين ومشاركة معرفتي.', kind: QuestionKind.likert, weight: 3, timeSeconds: 30),
    AssessmentQuestion(id: 'Q26', level: 'Level 2', text: 'أستطيع العمل بشكل منتج مع أشخاص لديهم أساليب عمل مختلفة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 35),
    AssessmentQuestion(id: 'Q27', level: 'Level 2', text: 'أضع أهدافًا طموحة ولكن واقعية لتطوري المهني.', kind: QuestionKind.likert, weight: 4, timeSeconds: 35),
    AssessmentQuestion(id: 'Q28', level: 'Level 2', text: 'أستطيع الحفاظ على معايير الجودة العالية حتى عند العمل بسرعة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 35),
    AssessmentQuestion(id: 'Q29', level: 'Level 2', text: 'أبني علاقات بنشاط مع أشخاص يمكنهم المساعدة في تطوير مسيرتي المهنية.', kind: QuestionKind.likert, weight: 3, timeSeconds: 40),
    AssessmentQuestion(id: 'Q30', level: 'Level 2', text: 'أستطيع تحديد الاتجاهات الناشئة التي قد تؤثر على مجال عملي.', kind: QuestionKind.likert, weight: 3, timeSeconds: 40),
    AssessmentQuestion(id: 'Q31', level: 'Level 2', text: 'أتعامل مع الانتقادات بشكل بناء وأستخدمها لتحسين أدائي.', kind: QuestionKind.likert, weight: 5, timeSeconds: 35),
    AssessmentQuestion(id: 'Q32', level: 'Level 2', text: 'أستطيع تبسيط العمليات المعقدة لجعلها أكثر كفاءة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 40),
    AssessmentQuestion(id: 'Q33', level: 'Level 2', text: 'أشعر بالراحة عند قيادة الاجتماعات والمناقشات الجماعية.', kind: QuestionKind.likert, weight: 3, timeSeconds: 30),
    AssessmentQuestion(id: 'Q34', level: 'Level 2', text: 'أستطيع تقدير المدة التي ستستغرقها المهام بدقة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 35),
    AssessmentQuestion(id: 'Q35', level: 'Level 2', text: 'أحافظ على العلاقات المهنية حتى بعد انتهاء المشاريع.', kind: QuestionKind.likert, weight: 3, timeSeconds: 30),
    AssessmentQuestion(id: 'Q36', level: 'Level 2', text: 'أستطيع فهم ثقافات الشركات المختلفة والتكيف معها بسرعة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 35),
    AssessmentQuestion(id: 'Q37', level: 'Level 2', text: 'أتخذ المبادرة لتحسين الأنظمة والعمليات في بيئة عملي.', kind: QuestionKind.likert, weight: 4, timeSeconds: 40),
    AssessmentQuestion(id: 'Q38', level: 'Level 2', text: 'أستطيع تحقيق التوازن بين احتياجات أصحاب المصلحة المتعددة عندما تتعارض.', kind: QuestionKind.likert, weight: 5, timeSeconds: 45),
    AssessmentQuestion(id: 'Q39', level: 'Level 2', text: 'أبقى محدثًا بأفضل ممارسات الصناعة والمنهجيات الجديدة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 35),
    AssessmentQuestion(id: 'Q40', level: 'Level 2', text: 'أستطيع العمل بفعالية في الهياكل التنظيمية الهرمية والمسطحة.', kind: QuestionKind.likert, weight: 3, timeSeconds: 40),
    AssessmentQuestion(id: 'Q41', level: 'Level 2', text: 'أسعى بنشاط للحصول على وجهات نظر متنوعة قبل اتخاذ القرارات المهمة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 40),
    AssessmentQuestion(id: 'Q42', level: 'Level 2', text: 'أستطيع الحفاظ على الحافز خلال المشاريع طويلة الأجل ذات المواعيد النهائية البعيدة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 35),
    AssessmentQuestion(id: 'Q43', level: 'Level 2', text: 'أتواصل بفعالية حول حالة المشروع والتقدم مع أصحاب المصلحة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 35),
    AssessmentQuestion(id: 'Q44', level: 'Level 2', text: 'أستطيع تحديد نقاط القوة الفردية لأعضاء فريقي وتطويرها.', kind: QuestionKind.likert, weight: 3, timeSeconds: 40),
    AssessmentQuestion(id: 'Q45', level: 'Level 2', text: 'أبقى منتجًا حتى عند العمل في ظروف أقل من مثالية.', kind: QuestionKind.likert, weight: 4, timeSeconds: 35),
    AssessmentQuestion(id: 'Q46', level: 'Level 2', text: 'أستطيع التفاوض على حلول مربحة للطرفين في المواقف الصعبة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 40),
    AssessmentQuestion(id: 'Q47', level: 'Level 2', text: 'أتوقع بنشاط المخاطر والمشكلات المحتملة وأبلغ الأطراف المعنية.', kind: QuestionKind.likert, weight: 5, timeSeconds: 40),
    AssessmentQuestion(id: 'Q48', level: 'Level 2', text: 'أستطيع الموازنة بين الحرية الإبداعية ومتطلبات العملاء والقيود.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q49', level: 'Level 2', text: 'أساهم بنشاط في مشاركة المعرفة وتوثيق أفضل الممارسات.', kind: QuestionKind.likert, weight: 3, timeSeconds: 40),
    AssessmentQuestion(id: 'Q50', level: 'Level 2', text: 'أستطيع الحفاظ على الحدود المهنية أثناء بناء علاقات دافئة مع العملاء.', kind: QuestionKind.likert, weight: 4, timeSeconds: 40),
    AssessmentQuestion(id: 'Q51', level: 'Level 2', text: 'صف وقتًا كان عليك فيه تعلم مهارة جديدة تمامًا بسرعة لمشروع. كيف تعاملت مع عملية التعلم؟', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 120),
    AssessmentQuestion(id: 'Q52', level: 'Level 2', text: 'أخبرني عن موقف كان عليك فيه العمل مع عضو فريق أو عميل صعب. كيف تعاملت مع العلاقة؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 150),
    AssessmentQuestion(id: 'Q53', level: 'Level 2', text: 'صف وقتًا حددت فيه مشكلة فاتت على الآخرين. ما كان نهجك في لفت الانتباه إليها؟', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 120),
    AssessmentQuestion(id: 'Q54', level: 'Level 2', text: 'أخبرني عن مشروع كان عليك فيه إدارة أولويات متعددة ومتنافسة. كيف قررت ما يجب التركيز عليه؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 150),
    AssessmentQuestion(id: 'Q55', level: 'Level 2', text: 'صف وقتًا تلقيت فيه انتقادات قاسية أو ملاحظات سلبية. كيف استجبت وماذا تعلمت؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 150),
    AssessmentQuestion(id: 'Q56', level: 'Level 2', text: 'أخبرني عن موقف كان عليك فيه شرح مفهوم تقني لشخص بدون خلفية تقنية.', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 120),
    AssessmentQuestion(id: 'Q57', level: 'Level 2', text: 'صف وقتًا اتخذت فيه المبادرة لحل مشكلة لم تكن مسؤوليتك الرسمية.', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 120),
    AssessmentQuestion(id: 'Q58', level: 'Level 2', text: 'أخبرني عن مشروع لم يسير كما هو مخطط. ما الخطأ الذي حدث وكيف تكيفت؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 180),
    AssessmentQuestion(id: 'Q59', level: 'Level 2', text: 'صف وقتًا كان عليك فيه العمل تحت ضغط زمني كبير. ما الاستراتيجيات التي استخدمتها لإدارة الموقف؟', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 120),
    AssessmentQuestion(id: 'Q60', level: 'Level 2', text: 'أخبرني عن موقف ساعدت فيه شخصًا آخر على تحقيق أهدافه أو حل مشكلته.', kind: QuestionKind.openEnded, weight: 3, timeSeconds: 120),
    AssessmentQuestion(id: 'Q61', level: 'Level 2', text: 'صف وقتًا كان عليك فيه اتخاذ قرار بمعلومات غير كاملة. كيف تقدمت؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 150),
    AssessmentQuestion(id: 'Q62', level: 'Level 2', text: 'أخبرني عن موقف كان عليك فيه تغيير نهجك أو استراتيجيتك في منتصف المشروع.', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 150),
    AssessmentQuestion(id: 'Q63', level: 'Level 2', text: 'صف وقتًا كان عليك فيه توصيل أخبار أو نتائج مخيبة للآمال لشخص ما. كيف تعاملت مع التواصل؟', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 150),
    AssessmentQuestion(id: 'Q64', level: 'Level 2', text: 'أخبرني عن موقف تجاوزت فيه ما هو متوقع منك.', kind: QuestionKind.openEnded, weight: 3, timeSeconds: 120),
    AssessmentQuestion(id: 'Q65', level: 'Level 2', text: 'صف وقتًا كان عليك فيه الموازنة بين الجودة والسرعة في عملك. ما كان نهجك؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 150),
    AssessmentQuestion(id: 'Q66', level: 'Level 2', text: 'ماذا ستفعل إذا طلب منك عميل إكمال مشروع تعرف أنه يفوق مستوى مهاراتك الحالي؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 90),
    AssessmentQuestion(id: 'Q67', level: 'Level 2', text: 'كيف تتعامل مع موقف يريد فيه العميل تغيير متطلبات المشروع بشكل كبير بعد بدء العمل؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 120),
    AssessmentQuestion(id: 'Q68', level: 'Level 2', text: 'ماذا ستفعل إذا اكتشفت خطأً في العمل الذي سلمته بالفعل للعميل؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 90),
    AssessmentQuestion(id: 'Q69', level: 'Level 2', text: 'كيف تتعامل مع موقف تحتاج فيه للعمل مع عضو فريق يفوّت المواعيد النهائية باستمرار؟', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 120),
    AssessmentQuestion(id: 'Q70', level: 'Level 2', text: 'ماذا ستفعل إذا تلقيت طلبين عاجلين من عملاء مختلفين في نفس الوقت؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 90),
    AssessmentQuestion(id: 'Q71', level: 'Level 2', text: 'كيف تتعامل مع موقف يتأخر فيه العميل باستمرار في السداد؟', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 120),
    AssessmentQuestion(id: 'Q72', level: 'Level 2', text: 'ماذا ستفعل إذا أدركت في منتصف المشروع أن تقديرك الأولي كان منخفضًا جدًا؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 120),
    AssessmentQuestion(id: 'Q73', level: 'Level 2', text: 'كيف تتعامل مع موقف تحتاج فيه لإعطاء ملاحظات بناءة لشخص أكبر منك؟', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 120),
    AssessmentQuestion(id: 'Q74', level: 'Level 2', text: 'ماذا ستفعل إذا طُلب منك العمل على مشروع يتعارض مع قيمك الشخصية؟', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 120),
    AssessmentQuestion(id: 'Q75', level: 'Level 2', text: 'كيف تتعامل مع موقف تحتاج فيه لتعلم تكنولوجيا جديدة بسرعة لتلبية احتياجات العميل؟', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 90),
    AssessmentQuestion(id: 'Q76', level: 'Level 2', text: 'ماذا ستفعل إذا أخذ عضو الفريق الفضل في عملك أمام العميل؟', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 120),
    AssessmentQuestion(id: 'Q77', level: 'Level 2', text: 'كيف تتعامل مع موقف تبدو فيه توقعات عميلك غير واقعية بالنظر إلى الميزانية والجدول الزمني؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 150),
    AssessmentQuestion(id: 'Q78', level: 'Level 2', text: 'ماذا ستفعل إذا اكتشفت أن منافسًا ينشر معلومات كاذبة عن جودة عملك؟', kind: QuestionKind.openEnded, weight: 3, timeSeconds: 120),
    AssessmentQuestion(id: 'Q79', level: 'Level 2', text: 'كيف تتعامل مع موقف تحتاج فيه لإنهاء علاقة عمل مع عميل إشكالي؟', kind: QuestionKind.openEnded, weight: 4, timeSeconds: 150),
    AssessmentQuestion(id: 'Q80', level: 'Level 2', text: 'ماذا ستفعل إذا عُرض عليك مشروع يمكن أن يطور مسيرتك المهنية بشكل كبير ولكنه يتطلب العمل بممارسات غير أخلاقية؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 150),

    // المستوى 3 (51 سؤالاً)
    AssessmentQuestion(id: 'Q81', level: 'Level 3', text: 'أستطيع تصميم وتنفيذ استراتيجيات شاملة تدمج وظائف أعمال متعددة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 45),
    AssessmentQuestion(id: 'Q82', level: 'Level 3', text: 'أتواصل بفعالية مقترحات القيمة التجارية المعقدة مع كبار المسؤولين التنفيذيين.', kind: QuestionKind.likert, weight: 5, timeSeconds: 45),
    AssessmentQuestion(id: 'Q83', level: 'Level 3', text: 'أطور الآخرين ليصبحوا قادة فكر وخبراء في مجالاتهم.', kind: QuestionKind.likert, weight: 4, timeSeconds: 40),
    AssessmentQuestion(id: 'Q84', level: 'Level 3', text: 'أنشئ أطرًا ومنهجيات يمكن للآخرين تبنيها لحل مشكلات مماثلة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q85', level: 'Level 3', text: 'أؤثر على معايير الصناعة وأفضل الممارسات من خلال خبرتي وقيادة الفكر.', kind: QuestionKind.likert, weight: 3, timeSeconds: 45),
    AssessmentQuestion(id: 'Q86', level: 'Level 3', text: 'أستطيع التنقل في السياسات التنظيمية المعقدة مع الحفاظ على المعايير الأخلاقية.', kind: QuestionKind.likert, weight: 5, timeSeconds: 45),
    AssessmentQuestion(id: 'Q87', level: 'Level 3', text: 'أصمم وأنفذ أنظمة قياس لتتبع النتائج الاستراتيجية طويلة المدى.', kind: QuestionKind.likert, weight: 4, timeSeconds: 50),
    AssessmentQuestion(id: 'Q88', level: 'Level 3', text: 'أستطيع تجميع المعلومات من تخصصات متعددة لخلق حلول مبتكرة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q89', level: 'Level 3', text: 'أدير توقعات أصحاب المصلحة بفعالية عبر مصالح متنوعة ومتنافسة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 45),
    AssessmentQuestion(id: 'Q90', level: 'Level 3', text: 'أستطيع قيادة مبادرات التحول التنظيمي مع الحفاظ على التميز التشغيلي.', kind: QuestionKind.likert, weight: 5, timeSeconds: 50),
    AssessmentQuestion(id: 'Q91', level: 'Level 3', text: 'أحدد المواهب الناشئة وأطورها قبل أن تصبح واضحة للآخرين.', kind: QuestionKind.likert, weight: 3, timeSeconds: 45),
    AssessmentQuestion(id: 'Q92', level: 'Level 3', text: 'أستطيع الموازنة بين متطلبات الأداء قصيرة المدى والأهداف الاستراتيجية طويلة المدى.', kind: QuestionKind.likert, weight: 5, timeSeconds: 50),
    AssessmentQuestion(id: 'Q93', level: 'Level 3', text: 'أخلق رؤى مقنعة تلهم الآخرين لتحقيق نتائج استثنائية.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q94', level: 'Level 3', text: 'أستطيع العمل بفعالية في مواقف غامضة للغاية بمعايير نجاح غير واضحة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q95', level: 'Level 3', text: 'أبني وأحافظ على التحالفات الاستراتيجية التي تخلق قيمة متبادلة بمرور الوقت.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q96', level: 'Level 3', text: 'أستطيع ترجمة المفاهيم المجردة إلى خطط عمل ملموسة بمقاييس واضحة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 50),
    AssessmentQuestion(id: 'Q97', level: 'Level 3', text: 'أحافظ على الفعالية والهدوء خلال فترات التوتر وعدم اليقين الممتدة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 40),
    AssessmentQuestion(id: 'Q98', level: 'Level 3', text: 'أستطيع تحديد فرص السوق الناشئة والاستفادة منها قبل المنافسين.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q99', level: 'Level 3', text: 'أدمج بفعالية الذكاء الثقافي في استراتيجيات وعمليات الأعمال العالمية.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q100', level: 'Level 3', text: 'أستطيع تصميم وقيادة مفاوضات متعددة الأطراف المعقدة لتحقيق نتائج مثالية.', kind: QuestionKind.likert, weight: 5, timeSeconds: 50),
    AssessmentQuestion(id: 'Q101', level: 'Level 3', text: 'أخلق أنظمة تعلم تطور باستمرار قدرات المنظمة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 50),
    AssessmentQuestion(id: 'Q102', level: 'Level 3', text: 'أستطيع التواصل والتأثير بفعالية عبر اختلافات القوة والسلطة الكبيرة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 45),
    AssessmentQuestion(id: 'Q103', level: 'Level 3', text: 'أصمم وأنفذ هياكل حوكمة توازن بين الاستقلالية والمساءلة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 50),
    AssessmentQuestion(id: 'Q104', level: 'Level 3', text: 'أستطيع الحفاظ على التركيز الاستراتيجي مع تكييف التكتيكات مع الظروف المتغيرة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 45),
    AssessmentQuestion(id: 'Q105', level: 'Level 3', text: 'أخلق قيمة من خلال ربط الأفكار والأشخاص والفرص التي تبدو غير مرتبطة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q106', level: 'Level 3', text: 'أستطيع القيادة من خلال التأثير عندما يكون لدي مسؤولية ولكن بدون سلطة رسمية.', kind: QuestionKind.likert, weight: 5, timeSeconds: 45),
    AssessmentQuestion(id: 'Q107', level: 'Level 3', text: 'أوازن بفعالية بين الشفافية والتحفظ في المواقف الحساسة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q108', level: 'Level 3', text: 'أستطيع تصميم وتسهيل العمليات التي تولد حلولًا مبتكرة من فرق متنوعة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 50),
    AssessmentQuestion(id: 'Q109', level: 'Level 3', text: 'أحافظ على منظور طويل المدى والصبر أثناء معالجة الاحتياجات التشغيلية الفورية.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q110', level: 'Level 3', text: 'أستطيع توسيع نطاق الممارسات الناجحة بفعالية عبر سياقات وبيئات مختلفة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q111', level: 'Level 3', text: 'أخلق وأحافظ على الثقة في المواقف عالية المخاطر والضغط.', kind: QuestionKind.likert, weight: 5, timeSeconds: 40),
    AssessmentQuestion(id: 'Q112', level: 'Level 3', text: 'أستطيع تحديد ومعالجة القضايا النظامية التي يراها الآخرون كحوادث معزولة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 50),
    AssessmentQuestion(id: 'Q113', level: 'Level 3', text: 'أوازن بفعالية بين القيم والأولويات المتعددة المتنافسة في صنع القرار.', kind: QuestionKind.likert, weight: 5, timeSeconds: 50),
    AssessmentQuestion(id: 'Q114', level: 'Level 3', text: 'أستطيع تصميم وتنفيذ تغيير مستدام يستمر بعد مشاركتي المباشرة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 50),
    AssessmentQuestion(id: 'Q115', level: 'Level 3', text: 'أخلق أمانًا نفسيًا يمكن الآخرين من المخاطرة الذكية والابتكار.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q116', level: 'Level 3', text: 'أستطيع التواصل بفعالية عبر اختلافات ثقافية ولغوية كبيرة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 40),
    AssessmentQuestion(id: 'Q117', level: 'Level 3', text: 'أصمم وأنفذ أنظمة ملاحظات تدفع التحسين المستمر والتعلم.', kind: QuestionKind.likert, weight: 4, timeSeconds: 50),
    AssessmentQuestion(id: 'Q118', level: 'Level 3', text: 'أستطيع الحفاظ على المحاذاة الاستراتيجية مع تشجيع المعارضة الإبداعية والوجهات النظر البديلة.', kind: QuestionKind.likert, weight: 4, timeSeconds: 50),
    AssessmentQuestion(id: 'Q119', level: 'Level 3', text: 'أدمج بفعالية الاعتبارات الأخلاقية في استراتيجية وعمليات الأعمال.', kind: QuestionKind.likert, weight: 5, timeSeconds: 45),
    AssessmentQuestion(id: 'Q120', level: 'Level 3', text: 'أستطيع تصميم وقيادة فرق افتراضية تحقق أداءً عاليًا عبر المناطق الزمنية والثقافات.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q121', level: 'Level 3', text: 'أخلق وأحافظ على الزخم للمبادرات طويلة المدى على الرغم من النكسات قصيرة المدى.', kind: QuestionKind.likert, weight: 4, timeSeconds: 45),
    AssessmentQuestion(id: 'Q122', level: 'Level 3', text: 'أستطيع الموازنة بفعالية بين الابتكار وإدارة المخاطر في البيئات غير المؤكدة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 50),
    AssessmentQuestion(id: 'Q123', level: 'Level 3', text: 'أصمم وأنفذ تخطيطًا للخلافة يضمن استمرارية المنظمة ونموها.', kind: QuestionKind.likert, weight: 3, timeSeconds: 50),
    AssessmentQuestion(id: 'Q124', level: 'Level 3', text: 'أستطيع الحفاظ على الموضوعية والفعالية عندما تكون المصالح الشخصية على المحك.', kind: QuestionKind.likert, weight: 5, timeSeconds: 45),
    AssessmentQuestion(id: 'Q125', level: 'Level 3', text: 'أخلق قيمة من خلال إدارة التقاطع بين التكنولوجيا والقدرات البشرية بشكل فعال.', kind: QuestionKind.likert, weight: 4, timeSeconds: 50),
    AssessmentQuestion(id: 'Q126', level: 'Level 3', text: 'أستطيع تصميم وتسهيل تجارب التعلم التي تحول طريقة تفكير الآخرين وتصرفاتهم.', kind: QuestionKind.likert, weight: 4, timeSeconds: 50),
    AssessmentQuestion(id: 'Q127', level: 'Level 3', text: 'أوازن بفعالية بين احتياجات أصحاب المصلحة وخلق قيمة المساهمين بمرور الوقت.', kind: QuestionKind.likert, weight: 4, timeSeconds: 50),
    AssessmentQuestion(id: 'Q128', level: 'Level 3', text: 'أستطيع الحفاظ على معايير الأداء العالية مع التكيف مع المتطلبات المتغيرة بسرعة.', kind: QuestionKind.likert, weight: 5, timeSeconds: 45),
    AssessmentQuestion(id: 'Q129', level: 'Level 3', text: 'أخلق وأتواصل بسرديات مقنعة توحد المجموعات المتنوعة حول هدف مشترك.', kind: QuestionKind.likert, weight: 4, timeSeconds: 50),
    AssessmentQuestion(id: 'Q130', level: 'Level 3', text: 'أستطيع تصميم وتنفيذ أنظمة قياس تلتقط القيمة الكمية والنوعية.', kind: QuestionKind.likert, weight: 4, timeSeconds: 55),
    AssessmentQuestion(id: 'Q131', level: 'Level 3', text: 'صِف تحدي القيادة الأكثر أهمية واجهته وكيف تعاملت مع تطوير الآخرين مع تحقيق الأهداف التنظيمية. ما الأطر أو المبادئ التي وجهت قراراتك؟', kind: QuestionKind.openEnded, weight: 5, timeSeconds: 300),
  ];
