import 'package:quiz/feature/assessment/data/models/assessment_question/assessment_question.dart';

final List<AssessmentQuestion> questionsEn = [
  // Level 1 (20 questions)
  AssessmentQuestion(
    id: 'Q1',
    level: 'Level 1',
    text: 'I can explain complex ideas in simple terms that others can easily understand.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q2',
    level: 'Level 1',
    text: 'I actively seek new learning opportunities to improve my skills.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 20,
  ),
  AssessmentQuestion(
    id: 'Q3',
    level: 'Level 1',
    text: 'When I commit to a deadline, I always deliver the work on time.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 20,
  ),
  AssessmentQuestion(
    id: 'Q4',
    level: 'Level 1',
    text: 'I enjoy tackling problems that do not have clear solutions.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q5',
    level: 'Level 1',
    text: 'I take the initiative to start projects without waiting for detailed instructions.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q6',
    level: 'Level 1',
    text: 'I adapt my communication style based on who I am speaking with.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q7',
    level: 'Level 1',
    text: 'I feel comfortable working independently for long periods.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 20,
  ),
  AssessmentQuestion(
    id: 'Q8',
    level: 'Level 1',
    text: 'I ask clarifying questions when instructions are unclear.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q9',
    level: 'Level 1',
    text: 'I remain motivated even when working on repetitive tasks.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q10',
    level: 'Level 1',
    text: 'I can identify the root cause of problems instead of only addressing symptoms.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q11',
    level: 'Level 1',
    text: 'I actively seek feedback to improve the quality of my work.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q12',
    level: 'Level 1',
    text: 'I feel confident presenting my ideas to others.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 20,
  ),
  AssessmentQuestion(
    id: 'Q13',
    level: 'Level 1',
    text: 'I can work effectively under pressure and tight deadlines.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q14',
    level: 'Level 1',
    text: 'I take responsibility for my mistakes without making excuses.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q15',
    level: 'Level 1',
    text: 'I enjoy learning about industries and topics outside my specialty.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q16',
    level: 'Level 1',
    text: 'What motivates you most when working on projects?',
    kind: QuestionKind.multipleChoice,
    weight: 3,
    timeSeconds: 45,
    options: [
      'Learning new skills',
      'Solving challenging problems',
      'Helping others achieve their goals',
      'Creating something unique',
      'Gaining recognition',
    ],
  ),
  AssessmentQuestion(
    id: 'Q17',
    level: 'Level 1',
    text: 'When faced with a difficult task, what is your first instinct?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 60,
    options: [
      'Break it into smaller steps',
      'Ask for help or guidance',
      'Search for similar examples',
      'Start experimenting immediately',
      'Take time to plan thoroughly',
    ],
  ),
  AssessmentQuestion(
    id: 'Q18',
    level: 'Level 1',
    text: 'How do you prefer to receive feedback on your work?',
    kind: QuestionKind.multipleChoice,
    weight: 2,
    timeSeconds: 45,
    options: [
      'Detailed written feedback',
      'Face-to-face discussion',
      'Quick verbal feedback',
      'Visual examples for improvements',
      'Self-assessment followed by discussion',
    ],
  ),
  AssessmentQuestion(
    id: 'Q19',
    level: 'Level 1',
    text: 'At what time of day are you most productive for focused work?',
    kind: QuestionKind.multipleChoice,
    weight: 2,
    timeSeconds: 30,
    options: [
      'Early morning (6–9 AM)',
      'Mid-morning (9–12 PM)',
      'Afternoon (12–4 PM)',
      'Evening (4–8 PM)',
      'Late night (8 PM+)',
    ],
  ),
  AssessmentQuestion(
    id: 'Q20',
    level: 'Level 1',
    text: 'When working with clients, what matters most to you?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 60,
    options: [
      'Clear project specifications',
      'Regular communication updates',
      'Creative freedom in execution',
      'Immediate payment terms',
      'Building long-term relationships',
    ],
  ),

  // Level 2 (60 questions)
  AssessmentQuestion(
    id: 'Q21',
    level: 'Level 2',
    text: 'I can influence others’ opinions using logical arguments and evidence.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q22',
    level: 'Level 2',
    text: 'I remain calm and focused when unexpected problems arise.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q23',
    level: 'Level 2',
    text: 'I actively contribute ideas and solutions in team discussions.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q24',
    level: 'Level 2',
    text: 'I can prioritize multiple projects effectively while facing competing deadlines.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q25',
    level: 'Level 2',
    text: 'I enjoy mentoring others and sharing my knowledge.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q26',
    level: 'Level 2',
    text: 'I can work productively with people who have different working styles.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q27',
    level: 'Level 2',
    text: 'I set ambitious but realistic goals for my professional development.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q28',
    level: 'Level 2',
    text: 'I can maintain high quality standards even when working fast.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q29',
    level: 'Level 2',
    text: 'I actively build relationships with people who can help my career grow.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q30',
    level: 'Level 2',
    text: 'I can spot emerging trends that may affect my field of work.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q31',
    level: 'Level 2',
    text: 'I handle criticism constructively and use it to improve my performance.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q32',
    level: 'Level 2',
    text: 'I can simplify complex processes to make them more efficient.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q33',
    level: 'Level 2',
    text: 'I feel comfortable leading meetings and group discussions.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q34',
    level: 'Level 2',
    text: 'I can estimate how long tasks will take accurately.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q35',
    level: 'Level 2',
    text: 'I maintain professional relationships even after projects end.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q36',
    level: 'Level 2',
    text: 'I can understand and adapt quickly to different company cultures.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q37',
    level: 'Level 2',
    text: 'I take initiative to improve systems and processes in my workplace.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q38',
    level: 'Level 2',
    text: 'I can balance the needs of multiple stakeholders when they conflict.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q39',
    level: 'Level 2',
    text: 'I keep up to date with industry best practices and new methodologies.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q40',
    level: 'Level 2',
    text: 'I can work effectively in both hierarchical and flat organizational structures.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q41',
    level: 'Level 2',
    text: 'I actively seek diverse perspectives before making important decisions.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q42',
    level: 'Level 2',
    text: 'I can maintain motivation during long-term projects with distant deadlines.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q43',
    level: 'Level 2',
    text: 'I communicate project status and progress effectively with stakeholders.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q44',
    level: 'Level 2',
    text: 'I can identify individual strengths in my team and help develop them.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q45',
    level: 'Level 2',
    text: 'I remain productive even when working under less-than-ideal conditions.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q46',
    level: 'Level 2',
    text: 'I can negotiate mutually beneficial solutions in difficult situations.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q47',
    level: 'Level 2',
    text: 'I proactively anticipate risks and issues and inform stakeholders.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q48',
    level: 'Level 2',
    text: 'I can balance creative freedom with client requirements and constraints.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q49',
    level: 'Level 2',
    text: 'I actively contribute to knowledge sharing and documenting best practices.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q50',
    level: 'Level 2',
    text: 'I can maintain professional boundaries while building warm client relationships.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q51',
    level: 'Level 2',
    text:
        'Describe a time you had to learn a completely new skill quickly for a project. How did you approach the learning process?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q52',
    level: 'Level 2',
    text:
        'Tell me about a situation where you had to work with a difficult team member or client. How did you handle the relationship?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q53',
    level: 'Level 2',
    text:
        'Describe a time you identified a problem others missed. How did you bring attention to it?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q54',
    level: 'Level 2',
    text:
        'Tell me about a project where you had to manage multiple competing priorities. How did you decide what to focus on?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q55',
    level: 'Level 2',
    text:
        'Describe a time you received harsh criticism or negative feedback. How did you respond and what did you learn?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q56',
    level: 'Level 2',
    text:
        'Tell me about a situation where you had to explain a technical concept to someone without a technical background.',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q57',
    level: 'Level 2',
    text:
        'Describe a time you took initiative to solve a problem that was not officially your responsibility.',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q58',
    level: 'Level 2',
    text:
        'Tell me about a project that did not go as planned. What went wrong and how did you adapt?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 180,
  ),
  AssessmentQuestion(
    id: 'Q59',
    level: 'Level 2',
    text:
        'Describe a time you had to work under extreme time pressure. What strategies did you use to manage the situation?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q60',
    level: 'Level 2',
    text:
        'Tell me about a situation where you helped someone else achieve their goals or solve their problem.',
    kind: QuestionKind.openEnded,
    weight: 3,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q61',
    level: 'Level 2',
    text:
        'Describe a time you had to make a decision with incomplete information. How did you proceed?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q62',
    level: 'Level 2',
    text:
        'Tell me about a situation where you had to change your approach or strategy mid-project.',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q63',
    level: 'Level 2',
    text:
        'Describe a time you had to deliver disappointing news or results to someone. How did you handle the communication?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q64',
    level: 'Level 2',
    text: 'Tell me about a time when you went above and beyond what was expected of you.',
    kind: QuestionKind.openEnded,
    weight: 3,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q65',
    level: 'Level 2',
    text:
        'Describe a time you had to balance quality and speed in your work. What approach did you take?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q66',
    level: 'Level 2',
    text:
        'What would you do if a client asked you to complete a project you know is beyond your current skill level?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 90,
  ),
  AssessmentQuestion(
    id: 'Q67',
    level: 'Level 2',
    text:
        'How would you handle a client who significantly changes project requirements after work has started?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q68',
    level: 'Level 2',
    text:
        'What would you do if you discovered a mistake in work you have already delivered to a client?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 90,
  ),
  AssessmentQuestion(
    id: 'Q69',
    level: 'Level 2',
    text:
        'How would you handle working with a team member who consistently misses deadlines?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q70',
    level: 'Level 2',
    text:
        'What would you do if you received two urgent requests from different clients at the same time?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 90,
  ),
  AssessmentQuestion(
    id: 'Q71',
    level: 'Level 2',
    text:
        'How would you handle a situation where a client repeatedly delays payment?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q72',
    level: 'Level 2',
    text:
        'What would you do if you realized mid-project that your initial estimate was far too low?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q73',
    level: 'Level 2',
    text:
        'How would you give constructive feedback to someone who is senior to you?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q74',
    level: 'Level 2',
    text:
        'What would you do if you were asked to work on a project that conflicts with your personal values?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q75',
    level: 'Level 2',
    text:
        'How would you handle needing to learn a new technology quickly to meet a client’s needs?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 90,
  ),
  AssessmentQuestion(
    id: 'Q76',
    level: 'Level 2',
    text:
        'What would you do if a team member took credit for your work in front of a client?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q77',
    level: 'Level 2',
    text:
        'How would you handle a situation where a client’s expectations seem unrealistic given the budget and timeline?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q78',
    level: 'Level 2',
    text:
        'What would you do if you discovered a competitor spreading false information about the quality of your work?',
    kind: QuestionKind.openEnded,
    weight: 3,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q79',
    level: 'Level 2',
    text:
        'How would you handle ending a working relationship with a problematic client?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q80',
    level: 'Level 2',
    text:
        'What would you do if offered a project that could significantly advance your career but requires working in unethical ways?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),

  // Level 3 (51 questions)
  AssessmentQuestion(
    id: 'Q81',
    level: 'Level 3',
    text:
        'I can design and implement comprehensive strategies that integrate multiple business functions.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q82',
    level: 'Level 3',
    text:
        'I communicate complex value propositions effectively to senior executives.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q83',
    level: 'Level 3',
    text: 'I develop others to become thought leaders and experts in their fields.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q84',
    level: 'Level 3',
    text:
        'I create frameworks and methodologies that others can adopt to solve similar problems.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q85',
    level: 'Level 3',
    text:
        'I influence industry standards and best practices through my expertise and thought leadership.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q86',
    level: 'Level 3',
    text:
        'I can navigate complex regulatory policies while maintaining ethical standards.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q87',
    level: 'Level 3',
    text:
        'I design and implement measurement systems to track long-term strategic outcomes.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q88',
    level: 'Level 3',
    text:
        'I can synthesize information from multiple disciplines to create innovative solutions.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q89',
    level: 'Level 3',
    text:
        'I manage stakeholder expectations effectively across diverse and competing interests.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q90',
    level: 'Level 3',
    text:
        'I can lead organizational transformation initiatives while maintaining operational excellence.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q91',
    level: 'Level 3',
    text:
        'I identify emerging talent and develop it before it becomes obvious to others.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q92',
    level: 'Level 3',
    text:
        'I can balance short-term performance requirements with long-term strategic objectives.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q93',
    level: 'Level 3',
    text:
        'I create compelling insights that inspire others to achieve exceptional outcomes.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q94',
    level: 'Level 3',
    text:
        'I can work effectively in highly ambiguous situations with unclear success criteria.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q95',
    level: 'Level 3',
    text:
        'I build and sustain strategic alliances that create mutual value over time.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q96',
    level: 'Level 3',
    text:
        'I can translate abstract concepts into concrete action plans with measurable metrics.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q97',
    level: 'Level 3',
    text:
        'I maintain effectiveness and composure during extended periods of stress and uncertainty.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q98',
    level: 'Level 3',
    text:
        'I can identify emerging market opportunities and capitalize on them before competitors.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q99',
    level: 'Level 3',
    text:
        'I effectively integrate cultural intelligence into global business strategies and operations.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q100',
    level: 'Level 3',
    text:
        'I can design and lead complex multi-party negotiations to achieve optimal outcomes.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q101',
    level: 'Level 3',
    text: 'I create learning systems that continuously develop organizational capabilities.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q102',
    level: 'Level 3',
    text:
        'I can communicate and influence effectively across large differences in power and authority.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q103',
    level: 'Level 3',
    text:
        'I design and implement governance structures that balance autonomy and accountability.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q104',
    level: 'Level 3',
    text:
        'I can maintain strategic focus while adapting tactics to changing conditions.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q105',
    level: 'Level 3',
    text:
        'I create value by connecting ideas, people, and opportunities that seem unrelated.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q106',
    level: 'Level 3',
    text:
        'I lead through influence when I have responsibility but no formal authority.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q107',
    level: 'Level 3',
    text:
        'I balance transparency and discretion effectively in sensitive situations.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q108',
    level: 'Level 3',
    text:
        'I can design and facilitate processes that generate innovative solutions from diverse teams.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q109',
    level: 'Level 3',
    text:
        'I keep a long-term perspective and patience while addressing immediate operational needs.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q110',
    level: 'Level 3',
    text:
        'I can scale successful practices effectively across different contexts and environments.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q111',
    level: 'Level 3',
    text:
        'I build and maintain trust in high-risk, high-pressure situations.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q112',
    level: 'Level 3',
    text:
        'I can identify and address systemic issues that others see as isolated incidents.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q113',
    level: 'Level 3',
    text:
        'I effectively balance competing values and priorities when making decisions.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q114',
    level: 'Level 3',
    text:
        'I can design and implement sustainable change that persists after my direct involvement.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q115',
    level: 'Level 3',
    text:
        'I create psychological safety that enables others to take smart risks and innovate.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q116',
    level: 'Level 3',
    text:
        'I can communicate effectively across major cultural and language differences.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q117',
    level: 'Level 3',
    text:
        'I design and implement feedback systems that drive continuous improvement and learning.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q118',
    level: 'Level 3',
    text:
        'I maintain strategic alignment while encouraging creative dissent and alternative viewpoints.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q119',
    level: 'Level 3',
    text:
        'I integrate ethical considerations effectively into business strategy and operations.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q120',
    level: 'Level 3',
    text:
        'I can design and lead virtual teams that deliver high performance across time zones and cultures.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q121',
    level: 'Level 3',
    text:
        'I create and sustain momentum for long-term initiatives despite short-term setbacks.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q122',
    level: 'Level 3',
    text:
        'I can balance innovation and risk management effectively in uncertain environments.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q123',
    level: 'Level 3',
    text:
        'I design and implement succession planning that ensures organizational continuity and growth.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q124',
    level: 'Level 3',
    text:
        'I maintain objectivity and effectiveness when personal interests are at stake.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q125',
    level: 'Level 3',
    text:
        'I create value by managing the intersection between technology and human capabilities effectively.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q126',
    level: 'Level 3',
    text:
        'I can design and facilitate learning experiences that transform how people think and behave.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q127',
    level: 'Level 3',
    text:
        'I balance stakeholder needs and long-term shareholder value creation over time.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q128',
    level: 'Level 3',
    text:
        'I maintain high performance standards while adapting quickly to changing requirements.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q129',
    level: 'Level 3',
    text:
        'I craft and communicate compelling narratives that unite diverse groups around a common purpose.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q130',
    level: 'Level 3',
    text:
        'I can design and implement measurement systems that capture both quantitative and qualitative value.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 55,
  ),
  AssessmentQuestion(
    id: 'Q131',
    level: 'Level 3',
    text:
        'Describe the most significant leadership challenge you faced and how you balanced developing others while achieving organizational goals. What frameworks or principles guided your decisions?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 300,
  ),
];
