import 'package:quiz/feature/assessment/data/models/assessment_question/assessment_question.dart';

final List<AssessmentQuestion> questionsEn = [
  // =============================================================
  // Level 1 (20 questions): Beginner - Self-Learning Fundamentals
  // =============================================================

  AssessmentQuestion(
    id: 'Q1',
    level: 'Level 1',
    text: 'I can focus on a single study task for an appropriate period without getting distracted.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q2',
    level: 'Level 1',
    text: 'When I encounter a new topic, I feel curious and want to learn more about it.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q3',
    level: 'Level 1',
    text: 'What is the first thing you do when asked to learn a completely new skill?',
    kind: QuestionKind.multipleChoice,
    weight: 3,
    timeSeconds: 45,
    options: [
      'I search for quick tutorial videos on YouTube.',
      'I look for a comprehensive book or article explaining the basics.',
      'I ask an expert in the field directly.',
      'I start with practical experimentation and learn from my mistakes.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q4',
    level: 'Level 1',
    text: 'I set small daily or weekly goals that are achievable.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q5',
    level: 'Level 1',
    text: 'When I fail in my first attempt, I...',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 45,
    options: [
      'Give up and move on to something else.',
      'Feel a little frustrated then try again.',
      'Try to analyze the reason for failure before trying again.',
      'Immediately ask a friend or teacher for help.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q6',
    level: 'Level 1',
    text: 'I believe in my ability to learn topics that seem difficult at first.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q7',
    level: 'Level 1',
    text: 'Name one tool (app, website, or even a notebook) you use to organize your time or tasks.',
    kind: QuestionKind.openEnded,
    weight: 3,
    timeSeconds: 60,
  ),
  AssessmentQuestion(
    id: 'Q8',
    level: 'Level 1',
    text: 'I find it easy to allocate specific time for study or learning each day.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q9',
    level: 'Level 1',
    text: 'Which of these statements best describes your way of thinking?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 45,
    options: [
      'I am good at certain things and not good at others.',
      'I believe I can become good at anything if I put in enough effort.',
      'Intelligence and talent are fixed traits that don\'t change much.',
      'I prefer to stick to tasks I know I can successfully complete.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q10',
    level: 'Level 1',
    text: 'I enjoy sharing what I learn with others.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q11',
    level: 'Level 1',
    text: 'When I get bored with a topic, I look for a new and fun way to learn it.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q12',
    level: 'Level 1',
    text: 'What motivates you most to learn?',
    kind: QuestionKind.multipleChoice,
    weight: 3,
    timeSeconds: 45,
    options: [
      'Getting high grades or a certificate.',
      'Genuine passion for the subject itself.',
      'Getting a better job in the future.',
      'Proving my abilities to others.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q13',
    level: 'Level 1',
    text: 'I ask for help when I\'m stuck on a problem.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q14',
    level: 'Level 1',
    text: 'I celebrate my small achievements to maintain my enthusiasm.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q15',
    level: 'Level 1',
    text: 'Briefly describe one topic you learned on your own outside of school or university that interested you.',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 90,
  ),
  AssessmentQuestion(
    id: 'Q16',
    level: 'Level 1',
    text: 'I know what my learning strengths are.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q17',
    level: 'Level 1',
    text: 'When starting a new project, what is your first step usually?',
    kind: QuestionKind.multipleChoice,
    weight: 3,
    timeSeconds: 45,
    options: [
      'Plan everything in detail before starting.',
      'Start implementing immediately.',
      'Gather necessary information and tools.',
      'Discuss the idea with someone else.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q18',
    level: 'Level 1',
    text: 'Taking regular breaks during study helps me focus better.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q19',
    level: 'Level 1',
    text: 'What is the ideal environment that helps you learn effectively?',
    kind: QuestionKind.multipleChoice,
    weight: 2,
    timeSeconds: 45,
    options: [
      'A completely quiet place by myself.',
      'A cafe or public place with some noise.',
      'With a group of friends studying together.',
      'The place doesn\'t matter, I can focus in any environment.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q20',
    level: 'Level 1',
    text: 'I feel satisfied with myself when I successfully complete a difficult task.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),

  // =================================================================
  // Level 2 (60 questions): Intermediate - Problem Solving, Collaboration & Adaptation
  // =================================================================

  AssessmentQuestion(
    id: 'Q21',
    level: 'Level 2',
    text: 'When I face a complex problem, the first thing I do is break it down into smaller parts.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q22',
    level: 'Level 2',
    text: 'You started an online training course but found its content boring and the instructor\'s style unattractive. What do you do?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 60,
    options: [
      'I stop the course immediately and look for a better alternative.',
      'I force myself to complete it because I paid for it.',
      'I try to find only the useful parts and skip the rest.',
      'I look for other sources on the same topic while continuing the course.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q23',
    level: 'Level 2',
    text: 'I can adapt to unexpected changes in my study or work plans.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q24',
    level: 'Level 2',
    text: 'I regularly look for ways to improve my current skills rather than being satisfied with what I know.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q25',
    level: 'Level 2',
    text: 'In a group project, one team member is not doing their tasks. What is your first action?',
    kind: QuestionKind.multipleChoice,
    weight: 5,
    timeSeconds: 60,
    options: [
      'Talk to them privately to understand the reason and offer help.',
      'Tell the team leader or supervisor about the problem immediately.',
      'Ignore it and do their work myself to avoid problems.',
      'Criticize them in front of the rest of the team to motivate them.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q26',
    level: 'Level 2',
    text: 'I am open to receiving constructive criticism and using it to develop myself.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q27',
    level: 'Level 2',
    text: 'Describe a situation where you faced difficulty learning something, and how you overcame it.',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q28',
    level: 'Level 2',
    text: 'I prefer working in a team with people who have different opinions and skills than me.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q29',
    level: 'Level 2',
    text: 'When learning a new programming language, I focus on building small projects to apply what I learn.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q30',
    level: 'Level 2',
    text: 'How do you determine if an online information source (article, video) is reliable or not?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 60,
    options: [
      'If it has a large number of views or likes.',
      'If the author or website is known and has a good reputation.',
      'If the information matches what I already know.',
      'If the design is attractive and the language used is strong.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q31',
    level: 'Level 2',
    text: 'I periodically review my progress toward my goals and adjust my plan if necessary.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q32',
    level: 'Level 2',
    text: 'What is the most important skill you think you need to develop in the next year to achieve your career goals? Why?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q33',
    level: 'Level 2',
    text: 'I can effectively manage my time to balance learning, work, and other commitments.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q34',
    level: 'Level 2',
    text: 'You have two urgent tasks: one is easy and boring, the other is difficult and enjoyable. Which one do you usually start with?',
    kind: QuestionKind.multipleChoice,
    weight: 3,
    timeSeconds: 60,
    options: [
      'Start with the easy and boring one to get it done quickly.',
      'Start with the difficult and enjoyable one because I\'m excited about it.',
      'Divide both tasks and work on parts of them alternately.',
      'Postpone the decision and do something else.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q35',
    level: 'Level 2',
    text: 'I feel comfortable stepping out of my "comfort zone" and trying new things.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q36',
    level: 'Level 2',
    text: 'I look for creative solutions to problems rather than always following traditional methods.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q37',
    level: 'Level 2',
    text: 'When working in a team, I make sure to listen to others\' viewpoints even if I disagree with them.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q38',
    level: 'Level 2',
    text: 'The best way to learn a new practical skill is:',
    kind: QuestionKind.multipleChoice,
    weight: 3,
    timeSeconds: 50,
    options: [
      'Intensive theoretical study first.',
      'Repeated practice and hands-on experience.',
      'Observing an expert performing it.',
      'A combination of theoretical study and practical application.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q39',
    level: 'Level 2',
    text: 'I know how to prioritize when I have many tasks.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q40',
    level: 'Level 2',
    text: 'Write an example of a goal you followed using the SMART method (Specific, Measurable, Achievable, Relevant, Time-bound).',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q41',
    level: 'Level 2',
    text: 'I can stay motivated to complete a long-term project even if I face obstacles.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q42',
    level: 'Level 2',
    text: 'You discovered an error in your colleague\'s part of a joint project, and this error might affect your work. How do you react?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 60,
    options: [
      'Talk to them privately and gently explain the error.',
      'Fix the error myself without telling them.',
      'Tell the team leader to handle the problem.',
      'Ignore the error and focus only on my part.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q43',
    level: 'Level 2',
    text: 'I use tools like Trello, Asana, or Notion to organize projects.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q44',
    level: 'Level 2',
    text: 'I find that explaining a difficult concept to someone else helps me understand it more deeply.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q45',
    level: 'Level 2',
    text: 'Describe a bad habit (like procrastination or distraction) and how you try to overcome it.',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q46',
    level: 'Level 2',
    text: 'When looking for a new job or opportunity, I make sure to update my resume and portfolio.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q47',
    level: 'Level 2',
    text: 'You\'ve learned the basics of a skill (like graphic design). What is your next step to become a professional?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 60,
    options: [
      'Look for real or volunteer projects to apply the skill.',
      'Take more advanced courses in the same field.',
      'Read specialized books and articles in this field.',
      'All of the above.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q48',
    level: 'Level 2',
    text: 'I can control feelings of frustration or stress when things don\'t go as planned.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q49',
    level: 'Level 2',
    text: 'When starting a new project idea, I care about studying the market and potential competitors.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q50',
    level: 'Level 2',
    text: 'What is your preferred way to receive feedback on your work?',
    kind: QuestionKind.multipleChoice,
    weight: 3,
    timeSeconds: 50,
    options: [
      'Direct and straightforward feedback, even if it\'s harsh.',
      'Written and detailed feedback that I can review later.',
      'A direct meeting to discuss the work face-to-face.',
      'Positive feedback first, then improvement points.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q51',
    level: 'Level 2',
    text: 'I understand the importance of building professional networks in my field.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q52',
    level: 'Level 2',
    text: 'Mention a project (personal or academic) you\'re proud of, and what did you learn from it?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q53',
    level: 'Level 2',
    text: 'I evaluate multiple options before making an important decision.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q54',
    level: 'Level 2',
    text: 'You realized that the tool you\'re using in your project is not the best. What do you do?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 60,
    options: [
      'Continue using it because changing it now would cost time and effort.',
      'Look for a better alternative and switch immediately.',
      'Evaluate the cost and time of switching to a new tool versus the expected benefit.',
      'Ask my team members or an expert for their opinion before deciding.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q55',
    level: 'Level 2',
    text: 'I allocate time for reflection and thinking about my performance and what I can improve.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q56',
    level: 'Level 2',
    text: 'I can express my ideas clearly and confidently during group discussions.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q57',
    level: 'Level 2',
    text: 'How do you deal with information overload when researching a new topic?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q58',
    level: 'Level 2',
    text: 'I prefer to have a mentor who guides me in my career path.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q59',
    level: 'Level 2',
    text: 'What is the importance of "Personal Branding" in your opinion?',
    kind: QuestionKind.multipleChoice,
    weight: 3,
    timeSeconds: 50,
    options: [
      'It\'s only important for celebrities and business owners.',
      'It helps showcase your skills and experience professionally.',
      'It\'s just self-promotion and not necessary.',
      'It helps gain followers on social media.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q60',
    level: 'Level 2',
    text: 'I make sure to document my work steps and results in the projects I work on.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q61',
    level: 'Level 2',
    text: 'Your idea for a group project was not accepted by the rest of the team. How do you handle the situation?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 60,
    options: [
      'Try to understand their reasons for rejection and discuss their concerns.',
      'Withdraw from the discussion and let them decide.',
      'Defend my idea strongly and try to convince them by all means.',
      'Get angry and feel that they don\'t appreciate my ideas.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q62',
    level: 'Level 2',
    text: 'I am responsible for my own learning and personal development.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q63',
    level: 'Level 2',
    text: 'What value do side projects add to your career path?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q64',
    level: 'Level 2',
    text: 'I feel curious to understand how things work around me.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q65',
    level: 'Level 2',
    text: 'I prefer to be an "expert" in one field rather than having "knowledge" in multiple fields.',
    kind: QuestionKind.likert,
    weight: 2,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q66',
    level: 'Level 2',
    text: 'When I make a mistake, I admit it and learn from it.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q67',
    level: 'Level 2',
    text: 'How do you balance quality and speed when working on a project with a tight deadline?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 60,
    options: [
      'Focus on speed to deliver the project on time even if quality is lower.',
      'Focus on high quality even if I\'m late on the deadline.',
      'Identify essential tasks (Must-have) and perfect them, and postpone secondary tasks (Nice-to-have).',
      'Work longer hours to try to achieve both quality and speed.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q68',
    level: 'Level 2',
    text: 'I can distinguish between "being busy" and "being productive".',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q69',
    level: 'Level 2',
    text: 'Describe an experience where you worked with a difficult person, and how you dealt with them.',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q70',
    level: 'Level 2',
    text: 'I look for opportunities to apply what I learn in the real world.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q71',
    level: 'Level 2',
    text: 'I believe that soft skills are no less important than technical skills.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q72',
    level: 'Level 2',
    text: 'What is the "Minimum Viable Product" (MVP)?',
    kind: QuestionKind.multipleChoice,
    weight: 3,
    timeSeconds: 60,
    options: [
      'A complete and perfect version of the product.',
      'The simplest version of the product that can solve the user\'s basic problem.',
      'A prototype that is not usable.',
      'The product after adding all the features requested by customers.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q73',
    level: 'Level 2',
    text: 'I feel excited about turning an idea into a real project.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q74',
    level: 'Level 2',
    text: 'I follow blogs or experts in my field to stay updated with the latest developments.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q75',
    level: 'Level 2',
    text: 'What is the importance of building a portfolio for you?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q76',
    level: 'Level 2',
    text: 'I can present my work to an audience.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q77',
    level: 'Level 2',
    text: 'You face a technical problem that you\'ve searched for a solution many times but couldn\'t find. What is the least effective action?',
    kind: QuestionKind.multipleChoice,
    weight: 3,
    timeSeconds: 60,
    options: [
      'Take a short break then return to the problem with a clear mind.',
      'Continue searching with the same keywords repeatedly.',
      'Reformulate the problem and post it on a specialized forum like Stack Overflow.',
      'Explain the problem to a colleague who might see it from a different perspective.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q78',
    level: 'Level 2',
    text: 'I see failure as an opportunity to learn, not as the end of the road.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q79',
    level: 'Level 2',
    text: 'I experiment with new tools and techniques even if they\'re not directly required of me.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q80',
    level: 'Level 2',
    text: 'What is the difference between "Empathy" and "Sympathy" in a work environment?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),

  // =========================================================================================
  // Level 3 (40 questions): Advanced - Project Simulation, Decision Making, and Advanced Skills
  // =========================================================================================

  AssessmentQuestion(
    id: 'Q81',
    level: 'Level 3',
    text: 'A client requests major modifications to the project one day before the final delivery date. These modifications were not part of the initial agreement. How do you respond?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 180,
  ),
  AssessmentQuestion(
    id: 'Q82',
    level: 'Level 3',
    text: 'I can lead a small team and distribute tasks effectively to achieve a common goal.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q83',
    level: 'Level 3',
    text: 'During your project presentation, someone interrupts you with a difficult question and harsh criticism of your work. What is your reaction?',
    kind: QuestionKind.multipleChoice,
    weight: 5,
    timeSeconds: 75,
    options: [
      'Defend my work aggressively and accuse them of not understanding.',
      'Thank them for their question, acknowledge the aspect that can be improved, then explain the logic behind my decisions.',
      'Ignore their question and continue the presentation.',
      'Get nervous and lose focus for the rest of the presentation.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q84',
    level: 'Level 3',
    text: 'I am comfortable negotiating deadlines or project scope with clients or managers.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q85',
    level: 'Level 3',
    text: 'You have an idea for a startup project. Describe in 3 main steps how you would validate this idea before starting to build it.',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 200,
  ),
  AssessmentQuestion(
    id: 'Q86',
    level: 'Level 3',
    text: 'I can make decisive decisions quickly based on incomplete information when the situation requires it.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q87',
    level: 'Level 3',
    text: 'You\'re a project manager and discovered the project will be delayed by two weeks. What is the most professional action?',
    kind: QuestionKind.multipleChoice,
    weight: 5,
    timeSeconds: 75,
    options: [
      'Wait until the last moment hoping we can compensate for the delay.',
      'Inform the client or management immediately of the expected delay, with explanation of reasons and a plan to handle it.',
      'Pressure the team to work extra hours and try to finish the project on time at any cost.',
      'Look for someone on the team to blame for the delay.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q88',
    level: 'Level 3',
    text: 'I build a portfolio that focuses on showing results and impact I\'ve created, not just listing tasks I\'ve done.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q89',
    level: 'Level 3',
    text: 'One of your top team members is going through difficult personal circumstances that significantly affect their performance. As team leader, how do you manage this situation?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 180,
  ),
  AssessmentQuestion(
    id: 'Q90',
    level: 'Level 3',
    text: 'I understand the basic principles of the Business Model Canvas.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q91',
    level: 'Level 3',
    text: 'You received two job offers: one from a large, stable company with good salary but in a routine role, and another from a startup with lower salary but in a challenging role with learning opportunities. How do you make your decision?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 180,
  ),
  AssessmentQuestion(
    id: 'Q92',
    level: 'Level 3',
    text: 'I can convert user feedback into actionable improvements in the product.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q93',
    level: 'Level 3',
    text: 'What is the importance of "Design Thinking" in problem solving?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 75,
    options: [
      'It\'s just a process to make products look better.',
      'It focuses on understanding and empathizing with the user as a first step to solving the problem.',
      'It\'s a strict linear process that cannot be deviated from.',
      'It\'s only used by designers and has no relation to other fields.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q94',
    level: 'Level 3',
    text: 'I actively look for opportunities to mentor less experienced people.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q95',
    level: 'Level 3',
    text: 'Write a short professional email to a potential client you haven\'t met before, offering your services and aiming to schedule a meeting.',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 240,
  ),
  AssessmentQuestion(
    id: 'Q96',
    level: 'Level 3',
    text: 'I understand the difference between "Leadership" and "Management".',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q97',
    level: 'Level 3',
    text: 'You\'re in a job interview and the interviewer asks: "What is your biggest weakness?" What is the most professional answer?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 75,
    options: [
      'Say "I\'m a perfectionist".',
      'Mention a real weakness and explain how you\'re working to improve it.',
      'Say that you don\'t have any major weaknesses.',
      'Mention a skill not required for the job as a weakness.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q98',
    level: 'Level 3',
    text: 'I can set and measure Key Performance Indicators (KPIs) to evaluate project success.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q99',
    level: 'Level 3',
    text: 'You\'re responsible for launching a new product. How do you create a simple marketing strategy to reach the first 100 users?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 240,
  ),
  AssessmentQuestion(
    id: 'Q100',
    level: 'Level 3',
    text: 'I can deal with ambiguity and uncertainty in an ever-changing work environment.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q101',
    level: 'Level 3',
    text: 'Your project failed to achieve the desired results. How do you report this failure to senior management?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 180,
  ),
  AssessmentQuestion(
    id: 'Q102',
    level: 'Level 3',
    text: 'I make sure to build strong professional relationships based on mutual trust and respect.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q103',
    level: 'Level 3',
    text: 'What is the best approach to resolve a conflict between two team members who have completely different views on how to perform a task?',
    kind: QuestionKind.multipleChoice,
    weight: 5,
    timeSeconds: 75,
    options: [
      'Choose the solution you think is best and impose it on them.',
      'Meet with them, allow each to present their viewpoint, and facilitate a discussion to reach a compromise or the best possible solution.',
      'Ask them to solve the problem between themselves without your intervention.',
      'Divide the task into two parts for each to work separately.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q104',
    level: 'Level 3',
    text: 'I have the courage to say "no" to tasks or projects that conflict with my priorities or values.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q105',
    level: 'Level 3',
    text: 'Describe a project you would like to build in your portfolio within the next six months, specifying the skills it would highlight.',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 200,
  ),
  AssessmentQuestion(
    id: 'Q106',
    level: 'Level 3',
    text: 'I can think strategically and connect daily tasks to long-term goals.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q107',
    level: 'Level 3',
    text: 'You have an opportunity to pitch your investment idea to an investor in just 60 seconds (Elevator Pitch). What would you say?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 240,
  ),
  AssessmentQuestion(
    id: 'Q108',
    level: 'Level 3',
    text: 'I am responsible not only for the quality of my work, but also for the positive impact on my team and work environment.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q109',
    level: 'Level 3',
    text: 'The technology you were an expert in has become outdated. What is your strategy to adapt to this change?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 75,
    options: [
      'Ignore new technologies and stick with what I know.',
      'Start allocating regular time to learn the new alternative technology.',
      'Look for another job that still uses the old technology.',
      'Wait until the company asks me to learn the new technology.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q110',
    level: 'Level 3',
    text: 'I understand the importance of writing clear documentation for the projects I work on.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q111',
    level: 'Level 3',
    text: 'How do you price your services as a freelancer for the first time?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 180,
  ),
  AssessmentQuestion(
    id: 'Q112',
    level: 'Level 3',
    text: 'I can give constructive feedback to my colleagues in a respectful and helpful way.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q113',
    level: 'Level 3',
    text: 'I see calculated risk-taking as an essential part of the innovation process.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q114',
    level: 'Level 3',
    text: 'You\'re about to finish a long project and feel exhausted and lacking motivation. How do you motivate yourself to complete the final part with the best possible quality?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 180,
  ),
  AssessmentQuestion(
    id: 'Q115',
    level: 'Level 3',
    text: 'I apply techniques like the "Eisenhower Matrix" (Urgent/Important) to prioritize my tasks.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q116',
    level: 'Level 3',
    text: 'When building a product or service, I put myself in the end user\'s shoes to understand their needs and challenges.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q117',
    level: 'Level 3',
    text: 'What is the "Agile" methodology in project management, and what is one of its main benefits compared to the "Waterfall" model?',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 200,
  ),
  AssessmentQuestion(
    id: 'Q118',
    level: 'Level 3',
    text: 'I can communicate effectively with both technical and non-technical team members.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q119',
    level: 'Level 3',
    text: 'At which stage of a project do you think getting feedback is most important?',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 75,
    options: [
      'During the planning stage before starting.',
      'In the middle of the project to evaluate progress.',
      'Right before the final delivery.',
      'Continuously and repeatedly throughout the project lifecycle.'
    ],
  ),
  AssessmentQuestion(
    id: 'Q120',
    level: 'Level 3',
    text: 'What is "Lifelong Learning" for you, and how do you plan to apply it in your career path?',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 240,
  ),
];