import 'package:quiz/feature/chat/data/models/assessment_question/assessment_question.dart';

 final List<AssessmentQuestion> questionsAr = [
  // المستوى 1 (20 سؤال)
  AssessmentQuestion(
    id: 'Q1',
    level: 'المستوى 1',
    text: 'أستطيع شرح الأفكار المعقدة بعبارات بسيطة يستطيع الآخرون فهمها بسهولة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q2',
    level: 'المستوى 1',
    text: 'أسعى بنشاط لفرص تعلم جديدة لتحسين مهاراتي.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 20,
  ),
  AssessmentQuestion(
    id: 'Q3',
    level: 'المستوى 1',
    text: 'عندما ألتزم بموعد نهائي، أقدّم العمل دائمًا في الوقت المحدد.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 20,
  ),
  AssessmentQuestion(
    id: 'Q4',
    level: 'المستوى 1',
    text: 'أستمتع بمواجهة المشكلات التي لا تملك حلولًا واضحة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q5',
    level: 'المستوى 1',
    text: 'أبادر لبدء المشاريع دون الانتظار للحصول على تعليمات مفصلة.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q6',
    level: 'المستوى 1',
    text: 'أكيّف أسلوب تواصلي بناءً على من أتحادث معه.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q7',
    level: 'المستوى 1',
    text: 'أشعر بالراحة عند العمل بشكل مستقل لفترات طويلة.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 20,
  ),
  AssessmentQuestion(
    id: 'Q8',
    level: 'المستوى 1',
    text: 'أطرح أسئلة توضيحية عندما تكون التعليمات غير واضحة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q9',
    level: 'المستوى 1',
    text: 'أظل متحفزًا حتى عند العمل على مهام متكررة.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q10',
    level: 'المستوى 1',
    text: 'أستطيع تحديد السبب الجذري للمشكلات بدلاً من معالجة الأعراض فقط.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q11',
    level: 'المستوى 1',
    text: 'أطلب ملاحظات بنشاط لتحسين جودة عملي.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q12',
    level: 'المستوى 1',
    text: 'أشعر بالثقة عند عرض أفكاري أمام الآخرين.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 20,
  ),
  AssessmentQuestion(
    id: 'Q13',
    level: 'المستوى 1',
    text: 'أستطيع العمل بفعالية تحت الضغط والمواعيد النهائية الضيقة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q14',
    level: 'المستوى 1',
    text: 'أتحمّل مسؤولية أخطائي دون اختلاق أعذار.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 25,
  ),
  AssessmentQuestion(
    id: 'Q15',
    level: 'المستوى 1',
    text: 'أستمتع بالتعرف على صناعات ومواضيع خارج تخصصي.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q16',
    level: 'المستوى 1',
    text: 'ما الذي يحفزك أكثر عند العمل على المشاريع؟',
    kind: QuestionKind.multipleChoice,
    weight: 3,
    timeSeconds: 45,
    options: [
      'تعلم مهارات جديدة',
      'حل المشكلات الصعبة',
      'مساعدة الآخرين على تحقيق أهدافهم',
      'ابتكار شيء فريد',
      'الحصول على التقدير',
    ],
  ),
  AssessmentQuestion(
    id: 'Q17',
    level: 'المستوى 1',
    text: 'عندما تواجه مهمة صعبة، ما رد فعلك الأول؟',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 60,
    options: [
      'تقسيمها إلى خطوات أصغر',
      'طلب المساعدة أو التوجيه',
      'البحث عن أمثلة مشابهة',
      'البدء بالتجربة فورًا',
      'أخذ الوقت للتخطيط بدقة',
    ],
  ),
  AssessmentQuestion(
    id: 'Q18',
    level: 'المستوى 1',
    text: 'كيف تفضّل تلقي الملاحظات حول عملك؟',
    kind: QuestionKind.multipleChoice,
    weight: 2,
    timeSeconds: 45,
    options: [
      'ملاحظات مكتوبة ومفصلة',
      'مناقشة وجهًا لوجه',
      'ملاحظات شفهية سريعة',
      'أمثلة مرئية للتحسينات',
      'تقييم ذاتي متبوعًا بمناقشة',
    ],
  ),
  AssessmentQuestion(
    id: 'Q19',
    level: 'المستوى 1',
    text: 'في أي وقت من اليوم تكون أكثر إنتاجية للعمل المركز؟',
    kind: QuestionKind.multipleChoice,
    weight: 2,
    timeSeconds: 30,
    options: [
      'الصباح الباكر (6–9 صباحًا)',
      'منتصف الصباح (9–12 ظهرًا)',
      'فترة بعد الظهر (12–4 مساءً)',
      'المساء (4–8 مساءً)',
      'وقت متأخر من الليل (بعد 8 مساءً)',
    ],
  ),
  AssessmentQuestion(
    id: 'Q20',
    level: 'المستوى 1',
    text: 'عند العمل مع العملاء، ما الأمر الأهم بالنسبة لك؟',
    kind: QuestionKind.multipleChoice,
    weight: 4,
    timeSeconds: 60,
    options: [
      'متطلبات مشروع واضحة',
      'تحديثات اتصال منتظمة',
      'حرية إبداعية في التنفيذ',
      'شروط دفع فورية',
      'بناء علاقات طويلة الأمد',
    ],
  ),

  // المستوى 2 (60 سؤال)
  AssessmentQuestion(
    id: 'Q21',
    level: 'المستوى 2',
    text: 'أستطيع التأثير في آراء الآخرين باستخدام الحجج المنطقية والأدلة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q22',
    level: 'المستوى 2',
    text: 'أبقى هادئًا ومركزًا عندما تظهر مشكلات غير متوقعة.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q23',
    level: 'المستوى 2',
    text: 'أُسهِم بنشاط بأفكار وحلول في مناقشات الفريق.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q24',
    level: 'المستوى 2',
    text: 'أستطيع ترتيب أولويات عدة مشاريع بفعالية في ظل مواعيد متضاربة.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q25',
    level: 'المستوى 2',
    text: 'أستمتع بتوجيه الآخرين ومشاركة معرفتي.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q26',
    level: 'المستوى 2',
    text: 'أستطيع العمل بفعالية مع أشخاص لهم أساليب عمل مختلفة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q27',
    level: 'المستوى 2',
    text: 'أضع أهدافًا طموحة لكنها واقعية لتطوري المهني.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q28',
    level: 'المستوى 2',
    text: 'أحافظ على معايير جودة عالية حتى عند العمل بسرعة.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q29',
    level: 'المستوى 2',
    text: 'أبني علاقات مع أشخاص يمكنهم المساعدة في نمو مساري المهني.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q30',
    level: 'المستوى 2',
    text: 'أستطيع كشف الاتجاهات الناشئة التي قد تؤثر على مجالي.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q31',
    level: 'المستوى 2',
    text: 'أتعامل مع النقد بشكل بنّاء وأستخدمه لتحسين أدائي.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q32',
    level: 'المستوى 2',
    text: 'أستطيع تبسيط العمليات المعقدة لجعلها أكثر كفاءة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q33',
    level: 'المستوى 2',
    text: 'أشعر بالراحة في قيادة الاجتماعات والمناقشات الجماعية.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q34',
    level: 'المستوى 2',
    text: 'أستطيع تقدير كم ستستغرق المهام بدقة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q35',
    level: 'المستوى 2',
    text: 'أحافظ على علاقات مهنية حتى بعد انتهاء المشاريع.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 30,
  ),
  AssessmentQuestion(
    id: 'Q36',
    level: 'المستوى 2',
    text: 'أفهم وأتكيف بسرعة مع ثقافات الشركات المختلفة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q37',
    level: 'المستوى 2',
    text: 'أبادر لتحسين الأنظمة والعمليات في مكان عملي.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q38',
    level: 'المستوى 2',
    text: 'أستطيع موازنة احتياجات عدة جهات معنية عندما تتعارض.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q39',
    level: 'المستوى 2',
    text: 'أواكب أفضل الممارسات والمنهجيات الجديدة في الصناعة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q40',
    level: 'المستوى 2',
    text: 'أستطيع العمل بفعالية في هياكل تنظيمية هرمية ومسطحة على حد سواء.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q41',
    level: 'المستوى 2',
    text: 'أسعى للحصول على وجهات نظر متنوعة قبل اتخاذ قرارات مهمة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q42',
    level: 'المستوى 2',
    text: 'أحافظ على الدافع خلال المشاريع طويلة الأمد ذات المواعيد البعيدة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q43',
    level: 'المستوى 2',
    text: 'أواصل التواصل بفعالية حول حالة المشروع وتقدمه مع الجهات المعنية.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q44',
    level: 'المستوى 2',
    text: 'أستطيع تحديد نقاط القوة الفردية في فريقي والمساعدة على تطويرها.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q45',
    level: 'المستوى 2',
    text: 'أظل منتجًا حتى عند العمل في ظروف أقل من المثالية.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 35,
  ),
  AssessmentQuestion(
    id: 'Q46',
    level: 'المستوى 2',
    text: 'أستطيع التفاوض على حلول تفيد جميع الأطراف في المواقف الصعبة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q47',
    level: 'المستوى 2',
    text: 'أستبق المخاطر والمشكلات وأعلم الجهات المعنية بها بشكل استباقي.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q48',
    level: 'المستوى 2',
    text: 'أستطيع موازنة الحرية الإبداعية مع متطلبات وقيود العميل.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q49',
    level: 'المستوى 2',
    text: 'أساهم بنشاط في مشاركة المعرفة وتوثيق أفضل الممارسات.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q50',
    level: 'المستوى 2',
    text: 'أحافظ على حدود مهنية أثناء بناء علاقات ودية مع العملاء.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q51',
    level: 'المستوى 2',
    text:
        'صِف موقفًا اضطررت فيه لتعلم مهارة جديدة تمامًا بسرعة لمشروع ما. كيف تعاملت مع عملية التعلم؟',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q52',
    level: 'المستوى 2',
    text:
        'اخبرني عن موقف اضطررت فيه للعمل مع عضو فريق أو عميل صعب. كيف تعاملت مع العلاقة؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q53',
    level: 'المستوى 2',
    text:
        'صِف موقفًا اكتشفت فيه مشكلة غفل عنها الآخرون. كيف لفت الانتباه إليها؟',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q54',
    level: 'المستوى 2',
    text:
        'اخبرني عن مشروع كان عليك إدارة أولويات مت competing عديدة. كيف قررت ما الذي تركز عليه؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q55',
    level: 'المستوى 2',
    text:
        'صِف موقفًا تلقيت فيه نقدًا حادًا أو ملاحظات سلبية. كيف استجبت وماذا تعلمت؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q56',
    level: 'المستوى 2',
    text:
        'اخبرني عن موقف اضطررت فيه لشرح مفهوم تقني لشخص ليس لديه خلفية تقنية.',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q57',
    level: 'المستوى 2',
    text:
        'صِف موقفًا بادرّت فيه لحل مشكلة لم تكن مسؤوليتك الرسمية. كيف فعلت ذلك؟',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q58',
    level: 'المستوى 2',
    text:
        'اخبرني عن مشروع لم يسر كما خططت له. ما الذي حدث وكيف تأقلمت؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 180,
  ),
  AssessmentQuestion(
    id: 'Q59',
    level: 'المستوى 2',
    text:
        'صِف موقفًا اضطررت فيه للعمل تحت ضغط زمني شديد. ما الاستراتيجيات التي استخدمتها لإدارة الوضع؟',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q60',
    level: 'المستوى 2',
    text:
        'اخبرني عن موقف ساعدت فيه شخصًا آخر على تحقيق أهدافه أو حل مشكلته.',
    kind: QuestionKind.openEnded,
    weight: 3,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q61',
    level: 'المستوى 2',
    text:
        'صِف موقفًا اضطررت فيه لاتخاذ قرار بمعلومات ناقصة. كيف تصرفت؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q62',
    level: 'المستوى 2',
    text:
        'اخبرني عن موقف اضطررت فيه لتغيير نهجك أو استراتيجيتك منتصف المشروع.',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q63',
    level: 'المستوى 2',
    text:
        'صِف موقفًا اضطررت فيه لإبلاغ شخص بنتائج مخيبة للآمال. كيف تعاملت مع التواصل؟',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q64',
    level: 'المستوى 2',
    text: 'اخبرني عن موقف بذلت فيه جهدًا إضافيًا يفوق المتوقع منك.',
    kind: QuestionKind.openEnded,
    weight: 3,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q65',
    level: 'المستوى 2',
    text:
        'صِف موقفًا كان عليك فيه موازنة الجودة والسرعة في عملك. ما النهج الذي اتبعته؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q66',
    level: 'المستوى 2',
    text:
        'ماذا ستفعل إذا طلب منك عميل تنفيذ مشروع تعلم أنه يتجاوز مستوى مهاراتك الحالية؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 90,
  ),
  AssessmentQuestion(
    id: 'Q67',
    level: 'المستوى 2',
    text:
        'كيف ستتعامل مع عميل يغير متطلبات المشروع بشكل كبير بعد بدء العمل؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q68',
    level: 'المستوى 2',
    text:
        'ماذا ستفعل إذا اكتشفت خطأً في عملك الذي سلمته بالفعل إلى عميل؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 90,
  ),
  AssessmentQuestion(
    id: 'Q69',
    level: 'المستوى 2',
    text:
        'كيف ستتعامل مع زميل في الفريق يتأخر باستمرار عن المواعيد النهائية؟',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q70',
    level: 'المستوى 2',
    text:
        'ماذا ستفعل إذا استلمت طلبين عاجلين من عميلين مختلفين في نفس الوقت؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 90,
  ),
  AssessmentQuestion(
    id: 'Q71',
    level: 'المستوى 2',
    text:
        'كيف ستتعامل مع موقف يؤخر فيه العميل السداد بشكل متكرر؟',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q72',
    level: 'المستوى 2',
    text:
        'ماذا ستفعل إذا أدركت منتصف المشروع أن تقديرك الأولي كان منخفضًا جدًا؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q73',
    level: 'المستوى 2',
    text:
        'كيف ستقدّم ملاحظات بناءة لشخص أعلى منك وظيفيًا؟',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q74',
    level: 'المستوى 2',
    text:
        'ماذا ستفعل إذا طُلب منك العمل على مشروع يتعارض مع قيمك الشخصية؟',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q75',
    level: 'المستوى 2',
    text:
        'كيف ستتعامل مع الحاجة لتعلم تكنولوجيا جديدة بسرعة لتلبية احتياجات عميل؟',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 90,
  ),
  AssessmentQuestion(
    id: 'Q76',
    level: 'المستوى 2',
    text:
        'ماذا ستفعل إذا نُسبت جهودك لشخص آخر أمام العميل؟',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q77',
    level: 'المستوى 2',
    text:
        'كيف ستتعامل مع موقف تبدو فيه توقعات العميل غير واقعية بالنظر إلى الميزانية والجدول الزمني؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q78',
    level: 'المستوى 2',
    text:
        'ماذا ستفعل إذا اكتشفت أن منافسًا ينشر معلومات زائفة عن جودة عملك؟',
    kind: QuestionKind.openEnded,
    weight: 3,
    timeSeconds: 120,
  ),
  AssessmentQuestion(
    id: 'Q79',
    level: 'المستوى 2',
    text:
        'كيف ستتعامل مع إنهاء علاقة عمل مع عميل إشكالي؟',
    kind: QuestionKind.openEnded,
    weight: 4,
    timeSeconds: 150,
  ),
  AssessmentQuestion(
    id: 'Q80',
    level: 'المستوى 2',
    text:
        'ماذا ستفعل إذا عُرض عليك مشروع يمكن أن يقدّم مسارك المهني بشكل كبير لكنه يتطلب أساليب غير أخلاقية؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 150,
  ),

  // المستوى 3 (51 سؤال)
  AssessmentQuestion(
    id: 'Q81',
    level: 'المستوى 3',
    text:
        'أستطيع تصميم وتنفيذ استراتيجيات شاملة تدمج عدة وظائف أعمال.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q82',
    level: 'المستوى 3',
    text:
        'أتواصل بفعالية عن عروض القيمة المعقدة أمام المسؤولين التنفيذيين الكبار.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q83',
    level: 'المستوى 3',
    text: 'أعمل على تطوير الآخرين ليصبحوا قادة فكر وخبراء في مجالاتهم.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q84',
    level: 'المستوى 3',
    text:
        'أبتكر أطرًا ومنهجيات يمكن للآخرين اعتمادها لحل مشكلات مماثلة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q85',
    level: 'المستوى 3',
    text:
        'أؤثر في معايير الصناعة وأفضل الممارسات من خلال خبرتي وقيادتي الفكرية.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q86',
    level: 'المستوى 3',
    text:
        'أستطيع التنقل خلال سياسات تنظيمية معقدة مع الحفاظ على المعايير الأخلاقية.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q87',
    level: 'المستوى 3',
    text:
        'أصمم وأنفذ أنظمة قياس لتتبع نتائج استراتيجية طويلة المدى.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q88',
    level: 'المستوى 3',
    text:
        'أستطيع تركيب معلومات من عدة تخصصات لابتكار حلول مبتكرة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q89',
    level: 'المستوى 3',
    text:
        'أدير توقعات الجهات المعنية بفعالية عبر مصالح متنوعة ومتنازعة.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q90',
    level: 'المستوى 3',
    text:
        'أستطيع قيادة مبادرات تحول تنظيمية مع الحفاظ على التميّز التشغيلي.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q91',
    level: 'المستوى 3',
    text:
        'أحدد المواهب الناشئة وأطورها قبل أن تصبح واضحة للآخرين.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q92',
    level: 'المستوى 3',
    text:
        'أوازن بين متطلبات الأداء قصيرة المدى والأهداف الاستراتيجية طويلة المدى.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q93',
    level: 'المستوى 3',
    text:
        'أبتكر رؤى مقنعة تلهم الآخرين لتحقيق نتائج استثنائية.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q94',
    level: 'المستوى 3',
    text:
        'أستطيع العمل بفعالية في ظروف غامضة للغاية مع معايير نجاح غير واضحة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q95',
    level: 'المستوى 3',
    text:
        'أبني وأحافظ على تحالفات استراتيجية تخلق قيمة متبادلة على المدى الطويل.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q96',
    level: 'المستوى 3',
    text:
        'أستطيع ترجمة المفاهيم المجردة إلى خطط عمل ملموسة بمقاييس قابلة للقياس.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q97',
    level: 'المستوى 3',
    text:
        'أحافظ على الفعالية والرباطة خلال فترات ممتدة من الضغط وعدم اليقين.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q98',
    level: 'المستوى 3',
    text:
        'أستطيع تحديد فرص سوقية ناشئة واستغلالها قبل المنافسين.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q99',
    level: 'المستوى 3',
    text:
        'أدمج الذكاء الثقافي بفعالية في استراتيجيات وعمليات الأعمال العالمية.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q100',
    level: 'المستوى 3',
    text:
        'أستطيع تصميم وقيادة مفاوضات معقدة متعددة الأطراف لتحقيق أفضل النتائج.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q101',
    level: 'المستوى 3',
    text: 'أبتكر أنظمة تعلم تطور قدرات المنظمة باستمرار.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q102',
    level: 'المستوى 3',
    text:
        'أستطيع التواصل والتأثير بفعالية عبر فروق كبيرة في القوة والسلطة.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q103',
    level: 'المستوى 3',
    text:
        'أصمم وأنفذ هياكل حوكمة توازن بين الاستقلالية والمساءلة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q104',
    level: 'المستوى 3',
    text:
        'أحافظ على التركيز الاستراتيجي مع تكييف التكتيكات لتغير الظروف.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q105',
    level: 'المستوى 3',
    text:
        'أخلق قيمة بربط الأفكار والأشخاص والفرص التي تبدو غير مرتبطة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q106',
    level: 'المستوى 3',
    text:
        'أقود بالتأثير عندما يكون لدي مسؤولية دون سلطة رسمية.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q107',
    level: 'المستوى 3',
    text:
        'أوازن بفعالية بين الشفافية والسرية في المواقف الحساسة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q108',
    level: 'المستوى 3',
    text:
        'أصمم وأُيسر عمليات تولّد حلولًا مبتكرة من فرق متنوعة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q109',
    level: 'المستوى 3',
    text:
        'أحتفظ بمنظور طويل الأمد وصبر أثناء معالجة الاحتياجات التشغيلية الفورية.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q110',
    level: 'المستوى 3',
    text:
        'أستطيع توسيع الممارسات الناجحة بفاعلية عبر سياقات وبيئات مختلفة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q111',
    level: 'المستوى 3',
    text:
        'أبني وأحافظ على الثقة في مواقف عالية المخاطر والضغط.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q112',
    level: 'المستوى 3',
    text:
        'أستطيع تحديد ومعالجة القضايا النظامية التي يرى الآخرون أنها حوادث معزولة.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q113',
    level: 'المستوى 3',
    text:
        'أوازن بفعالية بين القيم والأولويات المت competing عند اتخاذ القرارات.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q114',
    level: 'المستوى 3',
    text:
        'أستطيع تصميم وتنفيذ تغيير مستدام يستمر بعد انتهاء مشاركتي المباشرة.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q115',
    level: 'المستوى 3',
    text:
        'أخلق بيئة نفسية آمنة تمكن الآخرين من أخذ مخاطر محسوبة والابتكار.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q116',
    level: 'المستوى 3',
    text:
        'أستطيع التواصل بفعالية عبر اختلافات ثقافية ولغوية كبيرة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 40,
  ),
  AssessmentQuestion(
    id: 'Q117',
    level: 'المستوى 3',
    text:
        'أصمم وأنفذ أنظمة ملاحظات تدفع التحسين والتعلم المستمر.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q118',
    level: 'المستوى 3',
    text:
        'أحافظ على التوافق الاستراتيجي مع تشجيع الخلاف الإبداعي ووجهات النظر البديلة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q119',
    level: 'المستوى 3',
    text:
        'أدمج الاعتبارات الأخلاقية بفاعلية في استراتيجية وعمليات الأعمال.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q120',
    level: 'المستوى 3',
    text:
        'أستطيع تصميم وقيادة فرق افتراضية تحقق أداءً عاليًا عبر مناطق زمنية وثقافات مختلفة.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q121',
    level: 'المستوى 3',
    text:
        'أخلق وأحافظ على زخم للمبادرات طويلة الأمد رغم النكسات قصيرة الأمد.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q122',
    level: 'المستوى 3',
    text:
        'أوازن بين الابتكار وإدارة المخاطر بفعالية في بيئات غير مؤكدة.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q123',
    level: 'المستوى 3',
    text:
        'أصمم وأنفذ تخطيطًا للخلافة يضمن استمرارية ونمو المؤسسة.',
    kind: QuestionKind.likert,
    weight: 3,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q124',
    level: 'المستوى 3',
    text:
        'أحافظ على الموضوعية والفعالية عندما تكون المصالح الشخصية على المحك.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q125',
    level: 'المستوى 3',
    text:
        'أخلق قيمة بإدارة التقاطع بين التكنولوجيا والقدرات البشرية بفاعلية.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q126',
    level: 'المستوى 3',
    text:
        'أستطيع تصميم وتيسير تجارب تعلم تحول كيف يفكر الناس ويتصرفون.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q127',
    level: 'المستوى 3',
    text:
        'أوازن بين احتياجات الجهات المعنية وخلق قيمة للمساهمين على المدى الطويل.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q128',
    level: 'المستوى 3',
    text:
        'أحافظ على معايير أداء عالية مع التكيف السريع لمتطلبات متغيرة.',
    kind: QuestionKind.likert,
    weight: 5,
    timeSeconds: 45,
  ),
  AssessmentQuestion(
    id: 'Q129',
    level: 'المستوى 3',
    text:
        'أصوغ وأوصل سردًا مقنعًا يوحّد مجموعات متنوعة حول هدف مشترك.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 50,
  ),
  AssessmentQuestion(
    id: 'Q130',
    level: 'المستوى 3',
    text:
        'أستطيع تصميم وتنفيذ أنظمة قياس تلتقط القيمة الكمية والنوعية على حد سواء.',
    kind: QuestionKind.likert,
    weight: 4,
    timeSeconds: 55,
  ),
  AssessmentQuestion(
    id: 'Q131',
    level: 'المستوى 3',
    text:
        'صِف أهم تحدي قيادي واجهته وكيف وازنت بين تطوير الآخرين وتحقيق أهداف المؤسسة. ما الأطر أو المبادئ التي وجهت قراراتك؟',
    kind: QuestionKind.openEnded,
    weight: 5,
    timeSeconds: 300,
  ),
];
